import {
  SiHtml5,
  SiCss3,
  SiSass,
  SiJavascript,
  SiTailwindcss,
  SiReact,
  SiPython,
  SiBootstrap,
  SiCplusplus,
  SiFlask,
  SiVite,
  SiNextdotjs,
  SiPrisma,
  SiVercel,
  SiDocker,
  SiGit,
  SiGraphql,
  SiApollographql,
  SiFirebase,
} from "react-icons/si";
import { TbApi } from "react-icons/tb";

export const TECH = [
  { name: "HTML", Icon: SiHtml5 },
  { name: "CSS", Icon: SiCss3 },
  { name: "Sass", Icon: SiSass },
  { name: "JavaScript", Icon: SiJavascript },
  { name: "Tailwind", Icon: SiTailwindcss },
  { name: "React", Icon: SiReact },
  { name: "Python", Icon: SiPython },
  { name: "Bootstrap", Icon: SiBootstrap },
  { name: "C++", Icon: SiCplusplus },
  { name: "Flask", Icon: SiFlask },
  { name: "Vite", Icon: SiVite },
  { name: "Next.js", Icon: SiNextdotjs },
  { name: "Prisma", Icon: SiPrisma },
  { name: "Vercel", Icon: SiVercel },
  { name: "Docker", Icon: SiDocker },
  { name: "Git", Icon: SiGit },
  { name: "Nexus", Icon: TbApi },
  { name: "GraphQL", Icon: SiGraphql },
  { name: "Apollo", Icon: SiApollographql },
  { name: "Firebase", Icon: SiFirebase },
];
